commit-msg:
  commands:
    cog:
      run: cog verify --file {1}

pre-commit:
  parallel: true
  commands:
    lint:
      glob: "*.{js,ts,tsx,jsx}"
      run: bun run lint

pre-push:
  commands:
    cog:
      run: cog check
    lint:
      run: bun run lint
