name: Documentation Improvement
description: Suggest improvements to our documentation
title: "docs: "
labels: [ "documentation" ]
assignees: [ ]

body:
  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs improvement?
      options:
        - README
        - API Documentation
        - Code Comments
        - Examples/Tutorials
        - Installation Instructions
        - Configuration Guide
        - Other (please specify in description)
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Where is the documentation that needs improvement? (URL, file path, etc.)
      placeholder: e.g., README.md or https://github.com/user/repo/blob/main/docs/guide.md
    validations:
      required: true

  - type: textarea
    id: current-state
    attributes:
      label: Current State
      description: What does the current documentation say or not say?
      placeholder: The current documentation is missing information about...
    validations:
      required: true

  - type: textarea
    id: improvement
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      placeholder: I suggest adding/changing...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the documentation improvement here.
    validations:
      required: false
